version: '3.1'
services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST_FILE: /run/secrets/WORDPRESS_DB_HOST
      WORDPRESS_DB_USER_FILE: /run/secrets/WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME_FILE: /run/secrets/WORDPRESS_DB_NAME
    volumes:
      - ./docker/secrets:/run/secrets
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
